name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  local:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8.2', '3.8', '3.9', '3.10.2' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          pip install -e .
          pip install pytest
      - run: pytest
  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo not implemented
