name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  local:
    name: Unit tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [ '3.8.2', '3.9', '3.10', '3.11', '3.12' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -e '.[dev]'
      - name: Run pytest
        id: test
        continue-on-error: true
        run: pytest --cov=chris_plugin --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          env_vars: 'python-${{ matrix.python-version }}'
      - name: End test
        run: '[ "${{ steps.test.outcome }}" = "success" ]'

#  integration:
#    name: Integration tests
#    runs-on: ubuntu-latest
#    if: false
#    steps:
#      - run: echo not implemented
